name: Deploy ECS workflow

on:
  push:
    branches: [main]
    
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  

jobs:
  Deploy-ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::577573027390:role/github-cicd
          role-session-name: Mohitrolesession
          aws-region: us-east-1

      - name: Setup build
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/react-app:mohit
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition react-app-td \
          --query taskDefinition > task-definition.json

      - name: New image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: default
          image: ${{ steps.login-ecr.outputs.registry }}/react-app:mohit

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          wait-for-service-stability: false
          
      - name: Task Definition Variable
        id: taskdefintionvar
        shell: bash
        run: |
          echo "task_definition_arn=$(aws ecs describe-task-definition --task-definition react-app-td | jq '.[] | .taskDefinitionArn')" >> $GITHUB_OUTPUT
      
      - name: Task Defintion ARN
        run: |
          echo "Task Defintion: ${{ steps.taskdefintionvar.outputs.task_definition_arn }}"

      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: react-app-service
          cluster: react-app-cluster
          wait-for-service-stability: true
          wait-for-minutes: 10
